In [18]:
import pandas as pd
import numpy as np
import math
from miditime.miditime import MIDITime

In [19]:
time = pd.read_csv("data/time_series_data.csv")
others=pd.read_csv("data/other_information.csv")
location=pd.read_csv("data/location.csv")

In [58]:
time

,Combined_Key,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,1/28/20,1/29/20,1/30/20,...,5/26/20,5/27/20,5/28/20,5/29/20,5/30/20,5/31/20,6/1/20,6/2/20,6/3/20,6/4/20
0,"Guam, US",0,0,0,0,0,0,0,0,0,...,167,170,171,172,172,172,175,175,177,179
1,"Northern Mariana Islands, US",0,0,0,0,0,0,0,0,0,...,22,22,22,22,22,22,22,23,24,26
2,"Puerto Rico, US",0,0,0,0,0,0,0,0,0,...,3324,3397,3486,3647,3718,3776,3873,3935,4023,4508
3,"Virgin Islands, US",0,0,0,0,0,0,0,0,0,...,69,69,69,69,69,69,70,70,70,71
4,"Autauga, Alabama, US",0,0,0,0,0,0,0,0,0,...,189,192,205,212,216,221,233,239,239,241
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3035,"Central Utah, Utah, US",0,0,0,0,0,0,0,0,0,...,33,33,34,38,38,38,38,38,39,39
3036,"Southeast Utah, Utah, US",0,0,0,0,0,0,0,0,0,...,21,23,23,23,24,24,24,26,26,26
3037,"Southwest Utah, Utah, US",0,0,0,0,0,0,0,0,0,...,330,335,360,386,423,440,454,476,498,524
3038,"TriCounty, Utah, US",0,0,0,0,0,0,0,0,0,...,20,20,20,18,20,21,21,20,20,20
3039,"Weber-Morgan, Utah, US",0,0,0,0,0,0,0,0,0,...,272,273,276,288,293,298,303,308,316,330

In [20]:
workingWith=time.T

In [21]:
new_header=workingWith.iloc[0]
workingWith=workingWith[1:]
workingWith.columns=new_header

In [38]:
dailyGrowthMax=workingWith.diff(axis=0).max(axis=1)

In [23]:
maxofUSCaseGrowth=dailyGrowthMax.max(skipna=True)

In [24]:
central=workingWith.diff(axis=0)

In [34]:
central=central.iloc[1:,:]
central

Combined_Key,"Guam, US","Northern Mariana Islands, US","Puerto Rico, US","Virgin Islands, US","Autauga, Alabama, US","Baldwin, Alabama, US","Barbour, Alabama, US","Bibb, Alabama, US","Blount, Alabama, US","Bullock, Alabama, US",...,"Dukes and Nantucket,Massachusetts,US","Kansas City,Missouri,US","Michigan Department of Corrections (MDOC), Michigan, US","Federal Correctional Institution (FCI), Michigan, US","Bear River, Utah, US","Central Utah, Utah, US","Southeast Utah, Utah, US","Southwest Utah, Utah, US","TriCounty, Utah, US","Weber-Morgan, Utah, US"
1/24/20,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1/25/20,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1/26/20,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1/27/20,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1/28/20,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5/31/20,0,0,58,0,5,7,17,3,1,6,...,1,33,19,0,28,0,0,17,1,5
6/1/20,3,0,97,1,12,2,5,1,1,0,...,13,37,0,0,28,0,0,14,0,5
6/2/20,0,1,62,0,6,0,3,0,0,4,...,1,96,32,1,21,0,2,22,-1,5
6/3/20,2,1,88,0,0,0,2,0,0,2,...,0,51,5,2,38,1,0,22,0,8
6/4/20,2,2,485,1,2,1,0,0,0,2,...,1,71,17,3,28,0,0,26,0,14

In [26]:
for index,row in central.iterrows():
    for element in row:

SyntaxError: unexpected EOF while parsing (<ipython-input-26-a73f247c8699>, line 3)

In [57]:
testInput = central.iloc[120,:]
testInput.values

array([0, 0, 70, ..., 13, -1, 4], dtype=object)

In [42]:
mymidi = MIDITime(120, 'myfile.mid', base_octave=2, octave_range = 1)
noteList = []
c_major = ['C', 'D', 'E', 'F', 'G', 'A', 'B']

for element in testInput:
    if element > 0:
        noteList.append(mymidi.log_scale_pct(1, maxofUSCaseGrowth, central.iloc[120,-3], direction="log"))


# for d in testInput:
#     print(d)

# def setMidi(row):
#     thisMidi=[]
#     for element in row:
#         thisMidi.append(MIDITime(outfile="test.mid", ))

In [48]:
pd.Series(noteList).describe()

count    1.424000e+03
mean     2.860556e-01
std      5.553065e-17
min      2.860556e-01
25%      2.860556e-01
50%      2.860556e-01
75%      2.860556e-01
max      2.860556e-01
dtype: float64